config/routes.rb
JoyCorn::Application.routes.draw do
  root 'static_pages#index'

  devise_for :users
  resources :posts do
    collection do
      get 'view'
    end
  end
  post '/likes' => 'likes#create'
  delete '/likes' => 'likes#destroy'
  match 'page/:id' => 'static_pages#next', via:[:GET]
  get "static_pages/index"
  get "static_pages/help"
  get "static_pages/next"
  get "static_pages/search"

  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  resources :signed_urls, only: :index

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper_method :default_post_panel, :next_post_panel

  def index
    $current_index = 0
    $search_type = 'topic'
    $keyword = 'default'
    gon.global.current_menu = "#topics"
  end

  def help
  end

  def next
  end

  def search
    $current_index = 0
    $search_type = params[:search_type]
    $keyword = params[:keyword]
  end

  def default_post_panel
    temp = return_post_search_by($search_type, $keyword, 12, $current_index)
    $current_index = $current_index + 12
    temp
  end

  # return the next posts page to enable infinite scroll.
  def next_post_panel
    temp = return_post_search_by($search_type, $keyword, 3, $current_index)
    $current_index = $current_index + 3
    temp
  #  need to consider if there is search condition?
  end

  def return_post_default(post_number, start_point)
    Post.order(created_at: :desc).limit(post_number).offset(start_point)
  end

  def return_post_search_by(search_type, keyword, post_number, start_point)
    if search_type == 'topic'
      if keyword == 'default'
        return_post_default(post_number, start_point)
      end
    elsif search_type == 'type'
      Post.where(media_type: keyword).limit(post_number).offset(start_point).order(created_at: :desc)
    elsif search_type == 'tag'
      Tag.find_by_name(keyword).posts.limit(post_number).offset(start_point).order(created_at: :desc)
    elsif search_type == 'time'
      Post.where("created_at >= ?", keyword).limit(post_number).offset(start_point).order(created_at: :desc)
    elsif search_type == 'author'
      User.find_by_email(keyword).posts.limit(post_number).offset(start_point).order(created_at: :desc)
    else
    end
  end

  def post_filter(filter_type, keyword)
  #  filter the posts by keyword
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def get_popular_tags
    tag_hash = Hash.new(Tag.all.size)
    Tag.all.each do |tag|
    tag_hash[tag.name] = tag.posts.size
    end
    tag_hash.sort_by {|_, x| x}.reverse[0, 10]
  end

  def get_hottest(type, value, number)
  #  support load the famous posts or authors within a time
    if type == 'post'
      get_hottest_posts_by_time(value, number)
    elsif type == 'author'
      get_hottest_authors_by_time(value, number)
    else
    end
  
  end



  def get_like_number_by_post(post_id)
    Post.find(post_id).likes.size
  end

  def get_unlike_number_by_post(post_id)
    Post.find(post_id).unlikes.size
  end

  private

  def get_hottest_posts_by_time(value, number)
    Like.where("created_at > ?", value).select('post_id').order(post_id: :asc).group('post_id').limit(number)
  end

  def get_hottest_authors_by_time(value, number)

  end


  def get_proper_media_by_size(post, height, width)
    if post.instance_of?(Post)

    else
    end
  end

  module IpHelper

    def ip_to_int(ip_str)
      sub_ips = ip_str.to_s.split('.')
      ip_int = 0
      sub_ips.each do |sub_ip|
        ip_int = ip_int * 256 + sub_ip.to_s.to_i(10)
      end
      ip_int
    end

    def ip_masker(ip_str)
      sub_ips = ip_str.to_s.split('.')
      '[' + sub_ips[0] + '.' + sub_ips[1] + '.*' + ']'
    end

  end

end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<%= link_to 'Compose Post', new_post_path %>

app/views/static_pages/index.html.erb
<% @posts = default_post_panel %>
<!--Adjust the display of those posts.-->

<!--<div id="posts-panel" class="js-masonry" data-masonry-options='{ "itemSelector": "#posts-box"}'>-->
<div id="post-panel">
  <%= render 'shared/post' %>

  <div class="page-nav">
    <%# link_to('next page', static_pages_next_url, class: "next_post_panel") %>
    <a href="/page/2">next page</a>
  </div>
</div>

app/views/static_pages/next.html.erb
<% @posts = next_post_panel %>

<div id="post-panel">
  <%= render 'shared/post' %>

  <div class="page-nav">
    <%# link_to('next page', static_pages_next_url, class: "next_post_panel") %>
    <a href="/page/2">next page</a>
  </div>
</div>

app/views/static_pages/search.html.erb
<% @posts = default_post_panel %>
<!--Adjust the display of those posts.-->

<!--<div id="posts-panel" class="js-masonry" data-masonry-options='{ "itemSelector": "#posts-box"}'>-->
<div id="post-panel">
  <%= render 'shared/post' %>

  <div class="page-nav">
    <%# link_to('next page', static_pages_next_url, class: "next_post_panel") %>
    <a href="/page/2">next page</a>
  </div>
</div>